/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Conn;
import Controlador.CtrlPaciente;
import Modelo.Paciente;
import java.awt.Toolkit;
import java.util.LinkedList;

/**
 *
 * @author Felipe Erazo
 */
public class FormPpal extends javax.swing.JFrame {
    
    FormBackUp formBackUp;
    FormBuscador formBuscador;
    FormBuscador fb1;
    FormBuscador fb2;
    FormListado formListado;
    Conn conn;
    LinkedList<Paciente> pacientesCumpleanos;
    LinkedList<Paciente> pacientesControl;

    /**
     * Creates new form FormPpal
     */
    public FormPpal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Men\372 principal");
        setResizable(false);
        formBackUp = null;
        formBuscador = null;
        fb1 = null;
        fb2 = null;
        formListado = null;
        conn = new Conn();
        pacientesCumpleanos = new LinkedList();
        pacientesControl = new LinkedList();
        cargarCumpleanos();
        cargarControlesHoy();
    }
    
    public void cargarCumpleanos()
    {
        pacientesCumpleanos=new CtrlPaciente().listarCumpleanos();
        for(LinkedList l = conn.reporteSQL("SELECT cc, nombre, date_part('year', current_date)-date_part('year', fechanac) FROM pacientes WHERE date_part('month', fechanac)=date_part('month', current_date) AND date_part('day', fechanac)=date_part('day', current_date);"); !l.isEmpty(); list1.add((new StringBuilder()).append((String)l.removeFirst()).append(" (").append((String)l.removeFirst()).append(" a\361os)").toString())){}
            //listaPacientes.add(l.removeFirst());

    }

    public void cargarControlesHoy()
    {
        for(LinkedList l = conn.reporteSQL("SELECT p.cc, p.nombre FROM pacientes p, historias h WHERE p.cc=h.cc_paciente AND h.control=current_date;"); !l.isEmpty(); list2.add((new StringBuilder()).append((String)listaPacientes2.getLast()).append(" - ").append((String)l.removeFirst()).toString())){}
            //listaPacientes2.addLast(l.removeFirst());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnHistoriaClinica = new javax.swing.JButton();
        btnMiniControl = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();
        btnPaciente = new javax.swing.JButton();
        btnBackUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        list2 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/lupa.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnHistoriaClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/hist.png"))); // NOI18N
        btnHistoriaClinica.setText("Nueva Historia Clínica");
        btnHistoriaClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaClinicaActionPerformed(evt);
            }
        });

        btnMiniControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/mini.png"))); // NOI18N
        btnMiniControl.setText("Nuevo Mini Control");
        btnMiniControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiniControlActionPerformed(evt);
            }
        });

        btnMostrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/listar.png"))); // NOI18N
        btnMostrarTodo.setText("Mostrar todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/user-paciente.png"))); // NOI18N
        btnPaciente.setText("Nuevo Paciente");
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });

        btnBackUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/cajafuerte.png"))); // NOI18N
        btnBackUp.setText("Backup");
        btnBackUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUpActionPerformed(evt);
            }
        });

        jLabel1.setText("Cumpleaños:");

        jLabel2.setText("Controles para hoy:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnHistoriaClinica)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMiniControl))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnMostrarTodo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPaciente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBackUp)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBackUp, btnBuscar, btnHistoriaClinica, btnMiniControl, btnMostrarTodo, btnPaciente});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {list1, list2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnHistoriaClinica)
                    .addComponent(btnMiniControl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarTodo)
                    .addComponent(btnPaciente)
                    .addComponent(btnBackUp))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBackUp, btnBuscar, btnHistoriaClinica, btnMiniControl, btnMostrarTodo, btnPaciente});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {list1, list2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(formBuscador != null)
            formBuscador.dispose();
        formBuscador = new FormBuscador();
        formBuscador.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:
        if(formListado != null)
            formListado.dispose();
        formListado = new FormListado();
        formListado.cargarTodo();
        formListado.setVisible(true);
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnBackUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUpActionPerformed
        // TODO add your handling code here:
        if(formBackUp != null)
            formBackUp.dispose();
        formBackUp = new FormBackUp();
        formBackUp.setVisible(true);
    }//GEN-LAST:event_btnBackUpActionPerformed

    private void btnMiniControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiniControlActionPerformed
        // TODO add your handling code here:
        if(fb2 != null)
            fb2.dispose();
        fb2 = new FormBuscador();
        fb2.setEtiqueta("Busque el paciente para el nuevo mini control:");
        fb2.esNuevoMiniControl = true;
        fb2.setVisible(true);
    }//GEN-LAST:event_btnMiniControlActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        // TODO add your handling code here:
        FormPaciente formPaciente = new FormPaciente();
        formPaciente.limpiarForm();
        formPaciente.setSize(680, 430);
        formPaciente.setVisible(true);
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnHistoriaClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaClinicaActionPerformed
        // TODO add your handling code here:
        if(fb1 != null)
            fb1.dispose();
        fb1 = new FormBuscador();
        fb1.setEtiqueta("Busque el paciente para la nueva historia cl\355nica:");
        fb1.esNuevaHistoria = true;
        fb1.setVisible(true);
    }//GEN-LAST:event_btnHistoriaClinicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackUp;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnHistoriaClinica;
    private javax.swing.JButton btnMiniControl;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.List list1;
    private java.awt.List list2;
    // End of variables declaration//GEN-END:variables
}
